// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Anton (darkcite)

//! Hyperliquid L1 execution — the signing half (E2).
//!
//! E2 builds everything needed to produce a byte-exact, correctly
//! signed exchange action, and **nothing that can send one**. There is
//! no socket, no TLS, no HTTP and no host name in this crate: the
//! network arm lands in E3. Not one byte leaves the host from here.
//!
//! ## The one hard problem
//!
//! **LAW E-3 — msgpack key order is part of the signature.** The
//! action is hashed as MessagePack, and MessagePack preserves the
//! order keys were written in. A different order is a different hash
//! is a rejected order — and the rejection carries no hint, because
//! the signature itself is valid, just over a digest the venue did not
//! compute.
//!
//! This cannot be settled by reading documentation, so it is settled
//! against the venue's own signer: `tests/fixtures/hl/vectors.tsv`
//! holds 25 known-answer vectors generated by the official
//! `hyperliquid-python-sdk`, and `tests/hl_vectors.rs` asserts this
//! crate reproduces every one of them **byte for byte** — the msgpack,
//! the connection id, the EIP-712 digest and the 65-byte signature.
//!
//! ## Doctrine
//!
//! Zero allocation on the encode/sign path: every action is built into
//! a caller-owned `[u8; MAX_ACTION]`, prices and sizes render through a
//! stack `[u8; 24]`, and there is no `String`, no `Vec`, no `format!`
//! and no map anywhere in it. POD structs are `#[repr(C)]` + `Copy`.
//!
//! Fail-fast: an encode overflow is an error, never a truncation. A
//! half-written action that reached the signer would be a valid
//! signature over the wrong bytes, which is strictly worse than no
//! order at all.
//!
//! ## What is deliberately NOT here
//!
//! * `http.rs` — the TLS arm and `POST /exchange` (E3).
//! * `response.rs` — the zero-alloc response scanner (E3).
//! * `userws.rs` — the `userFills` lane feeding engine fill lane 3 (E4).
//! * `budget.rs` — the address request-budget governor (E4).

#![deny(missing_docs)]
#![forbid(unsafe_op_in_unsafe_fn)]
#![deny(clippy::missing_safety_doc, clippy::undocumented_unsafe_blocks)]

pub mod action;
pub mod asset;
pub mod msgpack;
pub mod nonce;
pub mod sign;
pub mod wire;

pub use action::{
    encode_batch_modify, encode_cancel, encode_cancel_by_cloid, encode_order, CancelByCloidWire,
    CancelWire, ModifyWire, OrderWire, Tif, MAX_ACTION, MAX_ORDERS,
};
pub use asset::{AssetError, AssetTable, ASSET_SLOTS};
pub use msgpack::{MsgPackErr, Writer};
pub use nonce::Nonce;
pub use sign::{connection_id, sign_action, Network, Vault};
pub use wire::{WireNum, WIRE_SCALE};
