// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Anton (darkcite)

//! Hyperliquid L1 execution — signing (E2) and the exchange arm (E3).
//!
//! E2 built everything needed to produce a byte-exact, correctly
//! signed exchange action and nothing that could send one. **E3 adds
//! the thing that sends it**: a mio + rustls HTTP/1.1 client
//! ([`http`]), the JSON request bodies ([`request`]), a fail-closed
//! answer scanner ([`response`]), the host/source interlock
//! ([`config`]) and the testnet gate ([`smoke`]).
//!
//! What has NOT changed is that nothing in this crate is reachable
//! from the engine yet: `cli::exec_boot::LIVE_ARM_VENUES` is still
//! empty, and a compile-time assertion holds it empty. The exchange
//! arm exists, is tested against a real TLS server, and is wired to
//! exactly one caller — the smoke, which cannot reach mainnet.
//!
//! ## The one hard problem
//!
//! **LAW E-3 — msgpack key order is part of the signature.** The
//! action is hashed as MessagePack, and MessagePack preserves the
//! order keys were written in. A different order is a different hash
//! is a rejected order — and the rejection carries no hint, because
//! the signature itself is valid, just over a digest the venue did not
//! compute.
//!
//! This cannot be settled by reading documentation, so it is settled
//! against the venue's own signer: `tests/fixtures/hl/vectors.tsv`
//! holds 25 known-answer vectors generated by the official
//! `hyperliquid-python-sdk`, and `tests/hl_vectors.rs` asserts this
//! crate reproduces every one of them **byte for byte** — the msgpack,
//! the connection id, the EIP-712 digest and the 65-byte signature.
//!
//! ## Doctrine
//!
//! Zero allocation on the encode/sign path: every action is built into
//! a caller-owned `[u8; MAX_ACTION]`, prices and sizes render through a
//! stack `[u8; 24]`, and there is no `String`, no `Vec`, no `format!`
//! and no map anywhere in it. POD structs are `#[repr(C)]` + `Copy`.
//!
//! Fail-fast: an encode overflow is an error, never a truncation. A
//! half-written action that reached the signer would be a valid
//! signature over the wrong bytes, which is strictly worse than no
//! order at all.
//!
//! ## The second hard problem: an answer that lies about itself
//!
//! Hyperliquid returns **HTTP 200 for rejections**, and buries
//! per-order errors *inside* a `status:"ok"` envelope. Two traps, one
//! shape. [`response::scan`] is therefore fail-closed: every shape it
//! does not positively recognise as an acceptance is a refusal, and
//! [`response::tests`] fuzzes it against arbitrary bytes to prove it
//! never panics and never invents an acceptance.
//!
//! ## What is deliberately NOT here
//!
//! * `HlExchange: OrderDispatch` — the engine-facing dispatcher (E4).
//!   It is not built speculatively: it belongs where the engine can
//!   actually reach it.
//! * The user-event WS TRANSPORT and the dispatcher worker that owns
//!   it. [`userws`] is the scanner half only; the socket belongs to
//!   the worker, which is the single writer of fill lane 3.
//!
//! ## What E4 added, and what still cannot reach the engine
//!
//! [`cloid`] (LAW E-9), [`budget`], [`userws`] and [`recon`] are
//! built and tested, and have **no production caller** — nothing
//! outside their own tests and the bench gate references them.
//! `cli::exec_boot::LIVE_ARM_VENUES` is still empty and still
//! compile-time asserted so.

#![deny(missing_docs)]
#![forbid(unsafe_op_in_unsafe_fn)]
#![deny(clippy::missing_safety_doc, clippy::undocumented_unsafe_blocks)]

pub mod action;
pub mod asset;
pub mod budget;
pub mod cloid;
pub mod config;
pub mod http;
pub mod lifecycle;
pub mod msgpack;
pub mod nonce;
pub mod recon;
pub mod request;
pub mod response;
pub mod selftest;
pub mod sign;
pub mod smoke;
pub mod userws;
pub mod wire;

pub use action::{
    encode_batch_modify, encode_cancel, encode_cancel_by_cloid, encode_order, CancelByCloidWire,
    CancelWire, ModifyWire, OrderWire, Tif, MAX_ACTION, MAX_ORDERS,
};
pub use asset::{AssetError, AssetTable, ASSET_SLOTS};
pub use budget::{AddressBudget, BudgetErr, BudgetGauge, INITIAL_BUFFER};
pub use cloid::{decode as decode_cloid, encode as encode_cloid, Owner, MAGIC as CLOID_MAGIC};
pub use config::{
    ConfigErr, HlConfig, Scope, ENV_AGENT_KEY, ENV_HOST, ENV_MASTER_ADDR, ENV_SOURCE,
    ENV_T_AGENT_KEY, ENV_T_HOST, ENV_T_MASTER_ADDR, ENV_T_SOURCE, HOST_MAINNET, HOST_TESTNET,
};
pub use http::{HlHttp, HttpErr, EXCHANGE_PATH, MAX_REQ_BODY, MAX_RESP_BUF};
pub use lifecycle::{LifecycleReport, LifecycleSpec};
pub use msgpack::{MsgPackErr, Writer};
pub use nonce::Nonce;
pub use request::{batch_modify_json, cancel_by_cloid_json, cancel_json, envelope, order_json};
pub use recon::{drift, net_exposure_1e8, scan_spot_state, SpotBalance};
pub use response::{scan, HlOk, HlResponse, ScanErr, Span};
pub use selftest::{SelfTestErr, SelfTestReport};
pub use sign::{connection_id, sign_action, Network, Vault};
pub use smoke::{
    SmokeErr, SmokeReport, EXIT_CORRUPT_ACCEPTED, EXIT_FAILED, EXIT_LIFECYCLE, EXIT_NOT_VERIFIED,
    EXIT_PASS, EXIT_SELFTEST, EXIT_UNREACHABLE,
};
pub use userws::{owner_of, scan_user_fills, to_fill, ConvertErr, TidRing, UserFill};
pub use wire::{WireNum, WIRE_SCALE};
