# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Anton (darkcite)
"""gen_settle_input -- writes ``settle-1.input.tsv`` (the HIP-4 settlement law).

LAW E-11 (BIN15 S1) as the harness implements it --
``cli::backtest::binary::settle_reference_1e6`` + ``payout_1e6`` -- and
its Python mirror (``claude_worker.hip4``, which the accrual's
``relabel`` lane labels every stored instance through, BIN15 S4) read
the same tape and must agree on every query, to the unit.

Grammar (one record per line, ``#`` comments and blanks skipped):

* ``S``                        -- a new mark series (the marks so far are cleared)
* ``M ts px``                  -- one mark, venue ns and ×1e6, ascending in a series
* ``Q expiry twap strike``     -- ``Q ref payout``, or ``Q - -`` when the evidence
                                  is not there

The series cover the law's branches: a whole window at 1-3 s cadence, the
gap bound to the nanosecond (a piece of exactly 10 s settles, 10 s + 1 ns
does not -- carried in from before the open, inside, and carried to the
expiry), a window whose open no mark covers, fewer than three marks
inside, marks exactly at the open and at the expiry, duplicate stamps,
a zero-width window (the daily families), and strikes placed on the
reference and one unit either side of it (``>=`` is the whole rule
there). Synthetic and seeded: no market data, nothing here is research.

Regenerate with ``cd claude-worker && uv run python
tests/fixtures/bin15/gen_settle_input.py``, then
``BIN15_SETTLE_WRITE=1 cargo nextest run -p cli the_settlement_law_matches_its_python_mirror``
and ``uv run pytest tests/test_hip4.py``. Changing this file changes the
fixture's identity -- add ``settle-2`` rather than rewriting a pinned one.

Convention: full ``import x`` only. No ``from x import y``.
"""

import pathlib

import claude_worker.hip4

S: int = 1_000_000_000
T0: int = 1_790_000_000 * S
W: int = 60 * S
GAP: int = claude_worker.hip4.SETTLE_MARK_GAP_MAX_NS


def _walk(n: int, seed: int, base: int, step: int) -> list[int]:
    """A deterministic integer price walk around ``base``."""
    out: list[int] = []
    s = seed
    px = base
    for _ in range(n):
        s = (s * 6364136223846793005 + 1442695040888963407) % (2**64)
        px += ((s >> 33) % (2 * step + 1)) - step
        out.append(max(px, 1))
    return out


def _queries(
    rows: list[str], ts: list[int], px: list[int], expiries: list[int], twaps: list[int]
) -> None:
    """Queries at every expiry x window, with strikes on the reference
    (the mirror's own value, so the boundary is tested exactly) and one
    unit either side; a fixed strike when there is no reference."""
    for e in expiries:
        for w in twaps:
            ref = claude_worker.hip4.settle_reference_1e6(ts, px, e, w)
            if ref is None:
                rows.append(f"Q\t{e}\t{w}\t{px[0]}")
                continue
            for k in (ref - 1, ref, ref + 1):
                rows.append(f"Q\t{e}\t{w}\t{k}")


def _series(rows: list[str], ts: list[int], px: list[int]) -> None:
    rows.append("S")
    for t, p in zip(ts, px, strict=True):
        rows.append(f"M\t{t}\t{p}")


def records() -> list[str]:
    rows: list[str] = [
        "# settle-1.input.tsv - the HIP-4 settlement law tape (LAW E-11, BIN15 S4).",
        "# Generated by tests/fixtures/bin15/gen_settle_input.py; do not hand-edit.",
        "#   S                      a new mark series",
        "#   M  ts px               one mark (venue ns, x1e6)",
        "#   Q  expiry twap strike  settle_reference_1e6 + payout_1e6",
    ]

    rows.append("# 1. a BTC-sized walk at a 1-3 s cadence: every window whole")
    ts: list[int] = []
    t = T0
    cadence = _walk(260, 20260924, 2, 1)
    for c in cadence:
        t += (1 + c % 3) * S + 7
        ts.append(t)
    px = _walk(len(ts), 1789, 77_177_000_000, 30_000_000)
    _series(rows, ts, px)
    _queries(rows, ts, px, [T0 + k * 13 * S + 11 for k in range(6, 40)], [W, 20 * S, 0])

    rows.append("# 2. the gap bound to the nanosecond: 10 s settles, 10 s + 1 ns does not")
    for piece in (GAP - 1, GAP, GAP + 1):
        ts = [T0 + k * piece for k in range(12)]
        px = _walk(len(ts), piece % 997, 2_510_500_000, 900_000)
        _series(rows, ts, px)
        # the piece carried in across the open, whole windows, the carry to the expiry
        ends = [ts[6] + 3 * S, ts[8], ts[9] + GAP - 1, ts[9] + GAP, ts[9] + GAP + 1, ts[11] + 5 * S]
        _queries(rows, ts, px, ends, [W])

    rows.append("# 3. a 15 s hole inside a 2 s series: windows across it are refused")
    ts = [T0 + k * 2 * S for k in range(60)]
    ts += [T0 + 118 * S + 15 * S + k * 2 * S for k in range(60)]
    px = _walk(len(ts), 4242, 78_553_000, 20_000)
    _series(rows, ts, px)
    _queries(rows, ts, px, [T0 + k * 10 * S for k in range(7, 30)], [W, 30 * S])

    rows.append("# 4. no mark in force at the open; fewer than three inside")
    ts = [T0 + 100 * S + k * 9 * S for k in range(10)]
    px = _walk(len(ts), 77, 12_345_000, 5_000)
    _series(rows, ts, px)
    ends = [T0 + 110 * S, T0 + 160 * S, T0 + 170 * S, T0 + 190 * S]
    _queries(rows, ts, px, ends, [W, 20 * S, 15 * S, 0])

    rows.append("# 5. marks exactly at the open and at the expiry; duplicate stamps")
    ts = []
    for k in range(40):
        ts.append(T0 + k * 3 * S)
        if k % 7 == 0:
            ts.append(T0 + k * 3 * S)
    px = _walk(len(ts), 9, 100_000_000, 400_000)
    _series(rows, ts, px)
    ends = [T0 + 60 * S, T0 + 63 * S, T0 + 90 * S, T0 + 99 * S, T0 + 117 * S]
    _queries(rows, ts, px, ends, [W, 30 * S, 0])

    rows.append("# 6. an empty series and a single mark")
    rows.append("S")
    rows.append(f"Q\t{T0}\t{W}\t1")
    rows.append(f"Q\t{T0}\t0\t1")
    rows.append("S")
    rows.append(f"M\t{T0}\t5000000")
    rows.append(f"Q\t{T0 + 5 * S}\t{W}\t5000000")
    rows.append(f"Q\t{T0 + 5 * S}\t0\t5000000")
    rows.append(f"Q\t{T0 + 5 * S}\t0\t5000001")
    return rows


def main() -> int:
    rows = records()
    out = pathlib.Path(__file__).with_name("settle-1.input.tsv")
    out.write_text("\n".join(rows) + "\n", encoding="utf-8")
    queries = sum(1 for r in rows if r.startswith("Q\t"))
    print(f"gen_settle_input: {len(rows)} line(s), {queries} quer(ies) -> {out}")
    return 0


if __name__ == "__main__":  # pragma: no cover - one-shot
    raise SystemExit(main())
