# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Anton (darkcite)
"""gen_clock_input -- writes ``clock-1.input.tsv`` (the BIN15 S2 clock fixture).

Synthetic, seeded, self-contained: ``(ts_ns, venue_time_ms)`` pairs in
file order, shaped like a Hyperliquid tick lane right after a boot --
thirty snapshots whose venue stamp is a minute or more old, then fresh
prints with 80-300 ms of feed delay, an unstamped tick every seventh row
and a 5-second outlier every five hundredth. No market data; nothing
here is research material.

Two laws read it: the harness's (``cli::backtest::clock::VenueOffsetFit``,
the median of the FIRST 64 stamped ticks) and
``claude_worker.hip4.venue_wall_offset_ns``'s (the median of 4 000
samples across the file). ``crates/cli`` writes ``clock-1.expected.tsv``
under ``BIN15_CLOCK_WRITE=1``; ``tests/test_hip4.py`` asserts the Python
mirror of the harness law equals it exactly and the file-wide law is
within one second of it.

Regenerate with ``cd claude-worker && uv run python
tests/fixtures/bin15/gen_clock_input.py``, then
``BIN15_CLOCK_WRITE=1 cargo nextest run -p cli -E 'test(the_clock_fixture)'``.

Convention: full ``import x`` only. No ``from x import y``.
"""

import pathlib

#: Monotonic stamp of the first row, ns.
TS0: int = 5_000_000_000_000
#: The TRUE venue - mono offset the rows are built on, ns.
OFFSET_NS: int = 1_789_000_000_000_000_000 - TS0
ROWS: int = 6_000


def records() -> list[str]:
    rows = [
        "# clock-1.input.tsv - the BIN15 S2 venue-clock tape. Generated by",
        "# tests/fixtures/bin15/gen_clock_input.py; do not hand-edit.",
        f"# true offset_ns {OFFSET_NS}",
        "# ts_ns\tvenue_time_ms   (0 = no venue stamp)",
    ]
    s = 20260924
    ts = TS0
    for k in range(ROWS):
        s = (s * 6364136223846793005 + 1442695040888963407) % (2**64)
        ts += 5_000_000 + (s >> 40) % 10_000_000  # 5-15 ms apart
        if k % 7 == 3:
            vms = 0
        elif k < 30:
            vms = (ts + OFFSET_NS - 60_000_000_000 - k * 1_000_000_000) // 1_000_000
        elif k % 500 == 0:
            vms = (ts + OFFSET_NS - 5_000_000_000) // 1_000_000
        else:
            delay = 80_000_000 + (s >> 20) % 220_000_000
            vms = (ts + OFFSET_NS - delay) // 1_000_000
        rows.append(f"{ts}\t{vms}")
    return rows


def main() -> int:
    out = pathlib.Path(__file__).with_name("clock-1.input.tsv")
    rows = records()
    out.write_text("\n".join(rows) + "\n", encoding="utf-8")
    print(f"gen_clock_input: {len(rows)} line(s) -> {out}")
    return 0


if __name__ == "__main__":  # pragma: no cover - one-shot
    raise SystemExit(main())
