# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Anton (darkcite)
"""gen_parity_input -- writes ``parity-1.input.tsv`` (the BIN15 pricer fixture).

Synthetic, seeded, self-contained: a deterministic integer walk of marks
around a handful of strikes, swept across all three recalibration
phases, plus every edge the pricer has a branch for -- the ±clamp, a
cold forecast, a zero horizon, a variance whose root floors to zero, a
non-positive price, the phase boundaries to the nanosecond, off-grid
interpolation in both tables, and the grid rounders on both signs. No
market data is involved; nothing here is research material.

**The tables travel in the fixture.** ``PHI`` and ``RECAL`` rows carry
the SHIPPED tables (``claude_worker.bin15_fit``, the same numbers
``bin15.toml.example`` holds and the engine hashes), so the parity pins
the table the member actually prices with rather than a test-local ramp
that could agree on both sides while shipping something else.

Regenerate with ``cd claude-worker && uv run python
tests/fixtures/bin15/gen_parity_input.py``, then
``BIN15_PARITY_WRITE=parity-1 cargo nextest run -p strategy-bin15 --test parity``
and ``uv run pytest tests/test_bin15_ref.py``. Changing this file changes
the fixture's identity -- add ``parity-2`` rather than rewriting a
pinned one.

Convention: full ``import x`` only. No ``from x import y``.
"""

import pathlib

import claude_worker.bin15_fit
import claude_worker.bin15_ref

#: The 15 m tenor, and the 8 h tenor the native-daily families price on.
TAU_15M_NS: int = 900_000_000_000
TAU_8H_NS: int = 28_800_000_000_000

#: A plausible per-minute variance of log-price ×1e18. σ_min = 10 bps of
#: log-price per minute is σ² ×1e18 = 1e12; the sweep walks around it.
SIG2_BASE: int = 1_000_000_000_000

#: Strikes ×1e6 -- one per O-Q7 underlying, at the orders of magnitude
#: the venue actually quotes (BTC, ETH, SOL, HYPE).
STRIKES: tuple[int, ...] = (
    77_177_000_000,
    2_510_500_000,
    78_553_000,
    12_345_000,
)

#: τ points, ns: inside each phase and exactly on both boundaries.
TAUS: tuple[int, ...] = (
    TAU_15M_NS,
    900_000_000_000,
    601_000_000_000,
    600_000_000_000,
    599_999_999_999,
    400_000_000_000,
    240_000_000_000,
    239_999_999_999,
    60_000_000_000,
    10_000_000_000,
    1_000_000_000,
    TAU_8H_NS,
)


def _walk(n: int, seed: int = 20260912) -> list[int]:
    """A deterministic integer walk in bps ×1e6 of the strike."""
    out: list[int] = []
    s = seed
    acc = 0
    for _ in range(n):
        s = (s * 6364136223846793005 + 1442695040888963407) % (2**64)
        acc += ((s >> 33) % 60_001) - 30_000
        out.append(acc)
    return out


def records() -> list[str]:
    """Every line of the fixture, in order."""
    phi = claude_worker.bin15_fit.phi_table_1e6()
    early = claude_worker.bin15_fit.recal_table_1e6(claude_worker.bin15_fit.SLOPE_EARLY_MILLI)
    mid = claude_worker.bin15_fit.recal_table_1e6(claude_worker.bin15_fit.SLOPE_MID_MILLI)
    late = claude_worker.bin15_fit.recal_table_1e6(claude_worker.bin15_fit.SLOPE_LATE_MILLI)

    rows: list[str] = [
        "# parity-1.input.tsv - the BIN15 pricer tape. Generated by",
        "# tests/fixtures/bin15/gen_parity_input.py; do not hand-edit.",
        "#   PHI   v0 .. v4096                    load the shipped Phi table",
        "#   RECAL phase v0 .. v64                load one shipped recal table",
        "#   F     mark strike tau sig2           fair_value",
        "#   X     mark strike                    log_moneyness_1e9",
        "#   P     d_1e6                          phi_1e6",
        "#   R     phase p_1e6                    recal_1e6",
        "#   H     tau_ns                         phase_of",
        "#   G     px_1e6 tick_1e6                floor_grid / ceil_grid",
        "PHI\t" + "\t".join(str(v) for v in phi),
        "RECAL\t0\t" + "\t".join(str(v) for v in early),
        "RECAL\t1\t" + "\t".join(str(v) for v in mid),
        "RECAL\t2\t" + "\t".join(str(v) for v in late),
    ]

    # --- phase_of, to the nanosecond ------------------------------
    rows.append("# phase_of on and around both boundaries")
    for tau in (0, 1, *TAUS, 239_999_999_998, 600_000_000_001, 10**15):
        rows.append(f"H\t{tau}")

    # --- log_moneyness: sign, scale and the refusals --------------
    rows.append("# log_moneyness: at the money, both directions, the refusals")
    for strike in STRIKES:
        for bps in (0, 1, -1, 10, -10, 100, -100, 1_000, -1_000, 5_000, -5_000):
            mark = strike + strike * bps // 10_000
            rows.append(f"X\t{mark}\t{strike}")
    for mark, strike in ((0, STRIKES[0]), (STRIKES[0], 0), (-1, 1), (1, 1), (2, 1)):
        rows.append(f"X\t{mark}\t{strike}")
    # A mark far enough above the strike that the second-order term is
    # large, and one where the result leaves i64 and is refused.
    rows.append(f"X\t{STRIKES[0] * 3}\t{STRIKES[0]}")
    # The U_CLAMP band's own edges -- u = 1e11 prices, one unit past it
    # refuses -- and the two cases that overflowed the i128 square
    # before O4b put the range check ahead of it.
    rows.append("X\t101000000\t1000000")
    rows.append("X\t102000000\t1000000")
    rows.append("X\t1000000000000000000\t1")
    rows.append(f"X\t{STRIKES[0]}\t1")
    # And fair_value must refuse the same inputs at the same place.
    rows.append(f"F\t{STRIKES[0]}\t1\t{TAU_15M_NS}\t{SIG2_BASE}")
    rows.append(f"F\t102000000\t1000000\t{TAU_15M_NS}\t{SIG2_BASE}")
    rows.append(f"F\t101000000\t1000000\t{TAU_15M_NS}\t{SIG2_BASE}")

    # --- phi_1e6: on grid, off grid, both ends --------------------
    rows.append("# phi_1e6: on grid, off grid (interpolation), the clamp")
    for d in (0, 1, 499, 500, 999, 1_000, 1_001, 137, 1_000_500, 1_960_000, 3_000_000):
        rows.append(f"P\t{d}")
    d = 0
    while d <= claude_worker.bin15_ref.D_CLAMP_1E6:
        rows.append(f"P\t{d}")
        d += 7_919  # deliberately coprime with the 1 000-unit grid
    rows.append(f"P\t{claude_worker.bin15_ref.D_CLAMP_1E6}")

    # --- recal_1e6: every phase, on and off the buckets -----------
    rows.append("# recal_1e6: every phase, on and off the buckets, out of range")
    for phase in range(claude_worker.bin15_ref.PHASES):
        for p in (-5, 0, 1, 15_624, 15_625, 15_626, 500_000, 999_999, 1_000_000, 2_000_000):
            rows.append(f"R\t{phase}\t{p}")
        p = 0
        while p <= 1_000_000:
            rows.append(f"R\t{phase}\t{p}")
            # Coprime with 15 625 (which is 5^6), so the sweep enters
            # every one of the 64 buckets at a different offset and the
            # interpolation is never only checked on a bucket edge.
            p += 2_111

    # --- fair_value: the walk across every strike and every tau ---
    rows.append("# fair_value: a seeded walk of marks x every strike x every tau")
    walk = _walk(64)
    for si, strike in enumerate(STRIKES):
        for tau in TAUS:
            for step in walk[si * 16 : si * 16 + 16]:
                mark = strike + strike * step // 10_000_000
                if mark <= 0:
                    continue
                sig2 = SIG2_BASE + (step % 7) * 100_000_000_000
                rows.append(f"F\t{mark}\t{strike}\t{tau}\t{sig2}")

    rows.append("# fair_value: the refusals and the saturations")
    k = STRIKES[0]
    for mark, strike, tau, sig2 in (
        (k, k, 0, SIG2_BASE),                 # no horizon
        (k, k, TAU_15M_NS, 0),                # cold forecast
        (k, k, TAU_15M_NS, -1),               # negative variance
        (0, k, TAU_15M_NS, SIG2_BASE),        # no mark
        (k, 0, TAU_15M_NS, SIG2_BASE),        # no strike
        (k, k, 1_000_000_000, 1),             # var floors to zero -> den 0
        (k, k, TAU_15M_NS, 1),                # tiny variance: the +clamp
        (k * 2, k, 600_000_000_000, 1),       # the + clamp, saturated
        (k // 2, k, 600_000_000_000, 1),      # the - clamp, saturated
        (k, k, TAU_15M_NS, 10**30),           # an absurd variance
        (k, k, TAU_8H_NS, SIG2_BASE),         # the daily tenor, at the money
    ):
        rows.append(f"F\t{mark}\t{strike}\t{tau}\t{sig2}")

    # --- the grid rounders ----------------------------------------
    rows.append("# floor_grid / ceil_grid: on grid, off grid, negative centres")
    for px in (0, 1, 50, 99, 100, 101, 400_000, 400_050, 999_900, 999_999, -1, -50, -100, -101):
        rows.append(f"G\t{px}\t100")
    for px in (0, 500_000, 1_000_001, -1):
        rows.append(f"G\t{px}\t1000000")

    return rows


def main() -> int:
    """Write the fixture beside this file."""
    rows = records()
    out = pathlib.Path(__file__).with_name("parity-1.input.tsv")
    out.write_text("\n".join(rows) + "\n", encoding="utf-8")
    ops = sum(1 for r in rows if r.split("\t")[0] in ("F", "X", "P", "R", "H", "G"))
    print(f"gen_parity_input: {len(rows)} line(s), {ops} op(s) -> {out}")
    return 0


if __name__ == "__main__":  # pragma: no cover - one-shot
    raise SystemExit(main())
