# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Anton (darkcite)
"""gen_parity2_input -- writes ``parity-2.input.tsv`` (BIN15 S3 pricer lanes).

``parity-1`` is the O4b tape and stays pinned as it is. BIN15 S3 (ruling
O-2) prices the binary on the venue's own settlement -- the TWAP of the
underlying's mark over ``[T - W, T]`` (LAW E-11) -- and its four new
records travel here:

* ``T`` -- ``pricing_horizon_ns``: the variance-time of that average, both
  branches, the continuity at ``tau = W``, and the ``u64`` extremes;
* ``S`` -- ``core_types::binary_twap_segment``: pieces inside, across and
  outside the window, plus a mark series folded piece by piece the way
  the member folds it;
* ``M`` -- ``twap_moneyness_1e9``: the running-TWAP moneyness and every
  refusal (a non-positive price or window, ``i128`` overflow, the band);
* ``W`` -- ``fair_value_twap``: a seeded walk of marks and known averages
  across every strike and horizon, outside and inside the window, and the
  edges (the tie that settles ITM, nothing left uncertain, a cold
  forecast).

Synthetic, seeded, self-contained: no market data, nothing here is
research material. The ``PHI`` / ``RECAL`` rows carry the SHIPPED tables
(``claude_worker.bin15_fit``), as ``parity-1``'s do.

Regenerate with ``cd claude-worker && uv run python
tests/fixtures/bin15/gen_parity2_input.py``, then
``BIN15_PARITY_WRITE=parity-2 cargo nextest run -p strategy-bin15 --test parity``
and ``uv run pytest tests/test_bin15_ref.py``. Changing this file changes
the fixture's identity -- add ``parity-3`` rather than rewriting a pinned
one.

Convention: full ``import x`` only. No ``from x import y``.
"""

import pathlib

import claude_worker.bin15_fit

#: One second, ns.
S_NS: int = 1_000_000_000

#: The venue's settlement window for the 15 m families, ns.
W_NS: int = 60 * S_NS

#: The 15 m tenor.
TAU_15M_NS: int = 900 * S_NS

#: sigma_min = 10 bps of log-price per minute => sigma^2 x1e18 = 1e12.
SIG2_BASE: int = 1_000_000_000_000

#: Strikes x1e6 at the orders of magnitude the venue quotes.
STRIKES: tuple[int, ...] = (
    77_177_000_000,
    2_510_500_000,
    78_553_000,
    12_345_000,
)

#: Time to expiry, ns: the window ahead, its open to the nanosecond, and
#: inside it down to the expiry.
TO_EXPIRY: tuple[int, ...] = (
    TAU_15M_NS,
    600 * S_NS,
    120 * S_NS,
    W_NS + 1,
    W_NS,
    W_NS - 1,
    45 * S_NS,
    29 * S_NS,
    10 * S_NS,
    1 * S_NS,
    1,
    0,
)

U64_MAX: int = 2**64 - 1
I128_MAX: int = 2**127 - 1


def _walk(n: int, seed: int) -> list[int]:
    """A deterministic integer walk in bps x1e6 of the strike."""
    out: list[int] = []
    s = seed
    acc = 0
    for _ in range(n):
        s = (s * 6364136223846793005 + 1442695040888963407) % (2**64)
        acc += ((s >> 33) % 60_001) - 30_000
        out.append(acc)
    return out


def _level(strike: int, step: int) -> int:
    """A price ``step`` x1e-7 of the strike away from it."""
    return strike + strike * step // 10_000_000


def records() -> list[str]:
    """Every line of the fixture, in order."""
    phi = claude_worker.bin15_fit.phi_table_1e6()
    early = claude_worker.bin15_fit.recal_table_1e6(claude_worker.bin15_fit.SLOPE_EARLY_MILLI)
    mid = claude_worker.bin15_fit.recal_table_1e6(claude_worker.bin15_fit.SLOPE_MID_MILLI)
    late = claude_worker.bin15_fit.recal_table_1e6(claude_worker.bin15_fit.SLOPE_LATE_MILLI)

    rows: list[str] = [
        "# parity-2.input.tsv - the BIN15 S3 pricer tape (the venue's settlement",
        "# law in the pricer). Generated by tests/fixtures/bin15/gen_parity2_input.py;",
        "# do not hand-edit.",
        "#   PHI   v0 .. v4096                    load the shipped Phi table",
        "#   RECAL phase v0 .. v64                load one shipped recal table",
        "#   T     to_expiry twap                 pricing_horizon_ns",
        "#   S     px from to open close          binary_twap_segment",
        "#   M     a mark strike to_expiry twap   twap_moneyness_1e9",
        "#   W     mark strike to_expiry twap a sig2   fair_value_twap",
        "PHI\t" + "\t".join(str(v) for v in phi),
        "RECAL\t0\t" + "\t".join(str(v) for v in early),
        "RECAL\t1\t" + "\t".join(str(v) for v in mid),
        "RECAL\t2\t" + "\t".join(str(v) for v in late),
    ]

    # --- T: the horizon, both branches, to the nanosecond ------------
    rows.append("# pricing_horizon_ns: every window x every distance, the extremes")
    windows = (0, 1, 2, 3, 4, 5, W_NS - 1, W_NS, W_NS + 1, W_NS + 2, 300 * S_NS, 65_535 * S_NS)
    for w in windows:
        for t in (0, 1, 2, w // 2, w // 3, w - 1 if w > 0 else 0, w, w + 1, 2 * w, 3 * w + 7,
                  TAU_15M_NS, 28_800 * S_NS, U64_MAX - 1, U64_MAX):
            rows.append(f"T\t{t}\t{w}")
    step = 0
    while step <= W_NS:
        rows.append(f"T\t{step}\t{W_NS}")
        step += 1_234_567_891  # off every second, so the cubic's floors vary

    # --- S: one piece at a time, then a folded series ----------------
    rows.append("# binary_twap_segment: inside, across both edges, outside, empty")
    k = STRIKES[0]
    open_ns = 1_790_000_000 * S_NS
    close_ns = open_ns + W_NS
    for frm, to in (
        (open_ns, close_ns),
        (open_ns - 5 * S_NS, open_ns + 3 * S_NS),
        (close_ns - 2 * S_NS, close_ns + 9 * S_NS),
        (open_ns - 9 * S_NS, close_ns + 9 * S_NS),
        (open_ns - 9 * S_NS, open_ns),
        (close_ns, close_ns + 1),
        (open_ns + 7, open_ns + 7),
        (open_ns + 9, open_ns + 3),
        (open_ns + 1, open_ns + 2),
    ):
        for px in (k, 1, 0, -k, 2**63 - 1):
            rows.append(f"S\t{px}\t{frm}\t{to}\t{open_ns}\t{close_ns}")
    rows.append(f"S\t{k}\t0\t{U64_MAX}\t0\t{U64_MAX}")
    rows.append(f"S\t{k}\t5\t9\t{U64_MAX}\t0")
    rows.append("# a mark series every 1-3 s, folded piece by piece as the member folds it")
    walk = _walk(48, seed=20260924)
    ts = open_ns - 2 * S_NS
    for i, stp in enumerate(walk):
        nxt = ts + (1 + (stp % 3 + 3) % 3) * S_NS + i * 1_000_003
        rows.append(f"S\t{_level(k, stp)}\t{ts}\t{nxt}\t{open_ns}\t{close_ns}")
        ts = nxt

    # --- M: the running-TWAP moneyness and its refusals ---------------
    rows.append("# twap_moneyness_1e9: a known average above / at / below, every distance")
    for strike in STRIKES:
        for t in (W_NS - 1, 45 * S_NS, 29 * S_NS, 10 * S_NS, 1, 0):
            for known_bps, mark_bps in ((50, -10), (-50, 10), (0, 0), (5, 5), (-1, 0)):
                known = strike + strike * known_bps // 10_000
                mark = strike + strike * mark_bps // 10_000
                a = known * (W_NS - t)
                rows.append(f"M\t{a}\t{mark}\t{strike}\t{t}\t{W_NS}")
    rows.append("# twap_moneyness_1e9: the refusals")
    for a, mark, strike, t, w in (
        (0, 0, k, 10 * S_NS, W_NS),            # no mark
        (0, k, 0, 10 * S_NS, W_NS),            # no strike
        (0, k, k, 10 * S_NS, 0),               # no window
        (I128_MAX, k, k, 10 * S_NS, W_NS),     # a nonsense average: overflow
        (-I128_MAX, k, k, 10 * S_NS, W_NS),
        (k * 10_000 * W_NS, k, k, 0, W_NS),    # |m| far past the band
        (0, 2**63 - 1, 1, U64_MAX, W_NS),      # X * 1e9 past i128
    ):
        rows.append(f"M\t{a}\t{mark}\t{strike}\t{t}\t{w}")

    # --- W: the walk, every strike x every distance -------------------
    rows.append("# fair_value_twap: a seeded walk of marks and known averages")
    walk = _walk(96, seed=20260923)
    for si, strike in enumerate(STRIKES):
        for t in TO_EXPIRY:
            for j in range(16):
                stp = walk[(si * 24 + j) % len(walk)]
                known_stp = walk[(si * 24 + j + 12) % len(walk)]
                mark = _level(strike, stp)
                known = _level(strike, known_stp)
                behind = W_NS - t if t < W_NS else 0
                a = known * behind
                sig2 = SIG2_BASE + (stp % 7) * 100_000_000_000
                rows.append(f"W\t{mark}\t{strike}\t{t}\t{W_NS}\t{a}\t{sig2}")

    rows.append("# fair_value_twap: the edges")
    for mark, strike, t, w, a, sig2 in (
        (k, k, 0, W_NS, k * W_NS, SIG2_BASE),               # the tie, nothing left: ITM
        (k, k, 0, W_NS, k * W_NS - 1, SIG2_BASE),           # one unit under: OTM
        (k - 1_000, k, 0, W_NS, (k + 1) * W_NS, SIG2_BASE),  # decided above
        (k, k, 1, W_NS, k * (W_NS - 1), SIG2_BASE),         # 1 ns left: den floors to 0
        (k, k, 30 * S_NS, W_NS, k * 30 * S_NS, SIG2_BASE),  # at the money inside
        (k, k, 30 * S_NS, W_NS, k * 30 * S_NS, 0),          # cold forecast
        (k, k, 30 * S_NS, W_NS, k * 30 * S_NS, -1),
        (0, k, 30 * S_NS, W_NS, k * 30 * S_NS, SIG2_BASE),  # no mark
        (k, k, 30 * S_NS, W_NS, I128_MAX, SIG2_BASE),       # a nonsense average
        (k, k, 30 * S_NS, W_NS, 0, SIG2_BASE),              # nothing folded: the far side
        (k, k, W_NS, W_NS, 0, SIG2_BASE),                   # the open: outside law
        (k, k, W_NS - 1, W_NS, 0, SIG2_BASE),               # a nanosecond inside
        (k, k, 600 * S_NS, 0, 0, SIG2_BASE),                # settles AT T: tau itself
        (k, k, 0, 0, 0, SIG2_BASE),                         # ... and at T, no horizon
        (k + k // 100, k, 120 * S_NS, W_NS, 0, 1),          # the + clamp, saturated
        (k - k // 100, k, 120 * S_NS, W_NS, 0, 1),          # the - clamp, saturated
        (k, k, 30 * S_NS, W_NS, k * 30 * S_NS, 10**30),     # an absurd variance
    ):
        rows.append(f"W\t{mark}\t{strike}\t{t}\t{w}\t{a}\t{sig2}")
    return rows


def main() -> int:
    """Write the fixture beside this file."""
    rows = records()
    out = pathlib.Path(__file__).with_name("parity-2.input.tsv")
    out.write_text("\n".join(rows) + "\n", encoding="utf-8")
    ops = sum(1 for r in rows if r.split("\t")[0] in ("T", "S", "M", "W"))
    print(f"gen_parity2_input: {len(rows)} line(s), {ops} op(s) -> {out}")
    return 0


if __name__ == "__main__":  # pragma: no cover - one-shot
    raise SystemExit(main())
