# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Anton (darkcite)
"""gen_parity_input -- writes ``parity-1.input.tsv`` (the xsd parity fixture).

Synthetic, seeded, self-contained: four cointegrated log-price paths (one
common random-walk factor with per-sym loadings + AR(1) idiosyncratic noise +
a handful of injected shocks) so that the spec-form decision table exercises
every branch -- long AND short entries, grid adds, revert / stop / max-hold
exits, a carried intent (an hour with no fresh tick) and absent holds.  No
market data is involved; nothing here is research material.

Regenerate with ``python3 gen_parity_input.py`` from this directory, then
``XSD_PARITY_WRITE=1 cargo nextest run -p strategy-xsd --test parity`` and
``uv run pytest tests/test_xsd_ref.py``.  Changing this file changes the
fixture's identity -- bump the name (``parity-2``) rather than rewriting a
pinned one.
"""

import math
import pathlib
import random

HOUR_NS: int = 3_600_000_000_000
SYMBOL_VENUE_SHIFT: int = 24
VENUE_BINANCE: int = 1
USDM_BASE: int = 512
WALL0_NS: int = 1_789_171_200 * 1_000_000_000   # 2026-09-12 00:00:00Z
WINDOW_H: int = 240
SEED_H: int = 240
LIVE_H: int = 480
DROP_RATE: float = 0.015

PARAMS: dict[str, int] = {
    "z_window_h": WINDOW_H,
    "z_enter_1e9": 2_000_000_000,
    "z_exit_1e9": 0,
    "z_stop_1e9": 3_500_000_000,
    "consensus": 1,
    "grid_n": 3,
    "grid_step_1e9": 500_000_000,
    "max_hold_h": 36,
    "cooldown_h": 1,
    "ttl_ns": 300_000_000_000,
    "position_usd_1e6": 1_000_000_000,
    "max_positions": 82,
    "max_gross_usd_1e6": 100_000_000_000,
    "direction": 1,
    "slip_1e9": 0,
}

BASES: list[float] = [math.log(100.0), math.log(2000.0), math.log(0.5), math.log(30.0)]
LOADINGS: list[float] = [1.0, 1.15, 0.9, 1.05]
# (hour offset from the first live hour, sym, log shock) -- the dislocations.
SHOCKS: list[tuple[int, int, float]] = [
    (20, 0, +0.045), (21, 0, +0.020),
    (70, 1, -0.050),
    (120, 2, +0.030), (121, 2, +0.030), (122, 2, +0.025),
    (180, 0, -0.040),
    (240, 3, +0.060),
    (300, 1, +0.035), (301, 1, +0.015),
    (360, 2, -0.045),
    (420, 0, +0.038), (421, 0, +0.012),
]
# (hour offset, sym) live hours with NO fresh tick, on top of the random
# drops -- placed on an hour whose open would have priced a fresh ENTER,
# so the fixture pins the carry law (the random drops alone missed it).
FORCED_DROPS: list[tuple[int, int]] = [(71, 0)]


def sym_id(i: int) -> int:
    return (VENUE_BINANCE << SYMBOL_VENUE_SHIFT) | (USDM_BASE + i)


def main() -> None:
    rng: random.Random = random.Random(20260912)
    n: int = len(BASES)
    hour0: int = WALL0_NS // HOUR_NS
    first: int = hour0 - SEED_H
    total: int = SEED_H + LIVE_H
    shocks: dict[tuple[int, int], float] = {(hour0 + h, s): v for h, s, v in SHOCKS}
    forced: set[tuple[int, int]] = {(hour0 + h, s) for h, s in FORCED_DROPS}
    factor: float = 0.0
    eps: list[float] = [0.0] * n
    closes: list[list[int]] = []
    for step in range(total):
        hour: int = first + step
        factor += rng.gauss(0.0, 0.006)
        row: list[int] = []
        for i in range(n):
            eps[i] = 0.97 * eps[i] + rng.gauss(0.0, 0.003) + shocks.get((hour, i), 0.0)
            lp: float = BASES[i] + LOADINGS[i] * factor + eps[i]
            row.append(max(2, int(round(math.exp(lp) * 1_000_000))))
        closes.append(row)
    lines: list[str] = [
        "# xsd parity fixture 1 (XSD-2). Consumed by crates/strategy-xsd/tests/parity.rs AND",
        "# claude-worker/tests/test_xsd_ref.py; the expected file beside it is written by the Rust",
        "# law (XSD_PARITY_WRITE=1) and asserted by both suites. Anchor law: wall_ns == mono_ns.",
        "# Generated by gen_parity_input.py (seeded; synthetic paths, not market data).",
        "# P params | A first live hour's open wall_ns | S sym | T target partner beta_1e9",
        "# C hour sym close_1e6 (seed) | K hour sym open_1e6 close_1e6 (live: ticks at open+1 s, open+3599 s)",
        "P " + " ".join("%s=%d" % (k, v) for k, v in PARAMS.items()),
        "A %d" % WALL0_NS,
    ]
    for i in range(n):
        lines.append("S %d" % sym_id(i))
    for t in range(3):
        for j in range(n):
            if j == t:
                continue
            beta: int = int(round(LOADINGS[t] / LOADINGS[j] * 1_000_000_000))
            lines.append("T %d %d %d" % (sym_id(t), sym_id(j), beta))
    for step in range(SEED_H):
        hour = first + step
        for i in range(n):
            lines.append("C %d %d %d" % (hour, sym_id(i), closes[step][i]))
    for step in range(SEED_H, total):
        hour = first + step
        for i in range(n):
            if (hour, i) in forced or (step > SEED_H and rng.random() < DROP_RATE):
                continue
            prev: int = closes[step - 1][i]
            opn: int = max(2, int(round(prev * (1.0 + rng.gauss(0.0, 0.0004)))))
            lines.append("K %d %d %d %d" % (hour, sym_id(i), opn, closes[step][i]))
    out: pathlib.Path = pathlib.Path(__file__).with_name("parity-1.input.tsv")
    out.write_text("\n".join(lines) + "\n")
    print("wrote", out, len(lines), "lines")


if __name__ == "__main__":
    main()
